### ISSUE TITLE
今天试了下GP，已复活了

### ISSUE THREAD

**Issue by github-xx** [dou4cc/goproxy#21]
(如果您是遇到本软件使用问题而并不清楚具体原因的话，请尽量提供更多信息，如软件版本，日志截图，地级运营商信息等。否则问题可能会被忽略或关闭)

**Comment by TangBaohua** [comment]
@github-xx 昨天试了下是很快了；有好用的IP段推荐吗？

**Comment by lazureice** [comment]
不是一直可以用嗎，有ip就行
